import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const notoSansArabic = localFont({
  src: "/fonts/NotoSansArabic-VariableFont_wdth,wght.ttf",
  variable: "--font-noto-arabic",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="fa" dir="rtl" className={`h-full antialiased`}>
      <body className={`min-h-full flex flex-col ${notoSansArabic.className}`}>
        {children}
      </body>
    </html>
  );
}
